### ISSUE TITLE
Error from daemon when running image

### ISSUE THREAD

**Issue by Meuge** [random-robbie/wifite2-docker#1]
I am trying to run the image but I get the next error: 
`Error response from daemon: oci runtime error: container_linux.go:265: starting container process caused "exec: \"python Wifite.py\": executable file not found in $PATH"` 

What can I do? Do I have to give privileges to the python script or set a path to the local machine in the command?

Thanks in advance!

**Comment by random-robbie** [comment]
I do a test on a fresh docker server tomorrow morning and let you know.

**Comment by random-robbie** [comment]
pixiewps is causing an issue during make I will continue to review and hopefully have a fix pushed soon.

**Comment by random-robbie** [comment]
Pixie wps issue fixed now sorting hashcat issue

**Comment by random-robbie** [comment]
Now Fixed. Docker image on hub should auto update also.

**Comment by Meuge** [comment]
It works like a charm, thanks a lot for the quick answer!
